# Generated by Django 4.2.11 on 2026-03-30 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='commissionrule',
            new_name='masters_com_party_i_f7d388_idx',
            old_name='masters_comm_party_i_idx',
        ),
        migrations.RenameIndex(
            model_name='commissionrule',
            new_name='masters_com_commodi_66e7e0_idx',
            old_name='masters_comm_commodit_idx',
        ),
        migrations.RenameIndex(
            model_name='commissionrule',
            new_name='masters_com_is_acti_27ce1e_idx',
            old_name='masters_comm_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='party',
            new_name='masters_par_party_c_73c65d_idx',
            old_name='masters_part_party_c_idx',
        ),
        migrations.RenameIndex(
            model_name='party',
            new_name='masters_par_party_t_3f14ee_idx',
            old_name='masters_part_party_t_idx',
        ),
        migrations.RenameIndex(
            model_name='party',
            new_name='masters_par_is_acti_d105be_idx',
            old_name='masters_part_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='warehouse',
            new_name='masters_war_warehou_c397af_idx',
            old_name='masters_ware_warehou_idx',
        ),
        migrations.RenameIndex(
            model_name='warehouse',
            new_name='masters_war_is_acti_2259ee_idx',
            old_name='masters_ware_is_acti_idx',
        ),
        migrations.AlterField(
            model_name='party',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['account_code'], name='masters_ban_account_e8c617_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['is_active'], name='masters_ban_is_acti_a0ef6b_idx'),
        ),
    ]
