# Generated by Django 4.2.11 on 2026-04-05 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_rename_masters_comm_party_i_idx_masters_com_party_i_f7d388_idx_and_more'),
        ('masters', '0002_unitofmeasure'),
    ]

    operations = [
    ]
