# Generated by Django 4.2.11 on 2026-03-20 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('aisle', models.CharField(max_length=50)),
                ('rack', models.CharField(max_length=50)),
                ('shelf', models.CharField(max_length=50)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('used_space', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'ordering': ['warehouse', 'code'],
            },
        ),
        migrations.CreateModel(
            name='InventoryValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_date', models.DateField(auto_now_add=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('method', models.CharField(choices=[('fifo', 'FIFO'), ('lifo', 'LIFO'), ('weighted', 'Weighted Average')], default='weighted', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('quantity_reserved', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('quantity_available', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reorder_point', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reorder_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_counted', models.DateField(blank=True, null=True)),
                ('last_received', models.DateField(blank=True, null=True)),
                ('last_issued', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['commodity', 'warehouse'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_date', models.DateField(auto_now_add=True)),
                ('quantity_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('variance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.CharField(choices=[('recount', 'Recount'), ('damage', 'Damage'), ('loss', 'Loss'), ('error', 'Error in Recording'), ('expiry', 'Expiry'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-adjustment_date'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer'), ('damaged', 'Damaged'), ('expired', 'Expired')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('capacity', models.DecimalField(decimal_places=2, help_text='Capacity in default unit', max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
