# Generated by Django 4.2.11 on 2026-03-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_rename_masters_comm_party_i_idx_masters_com_party_i_f7d388_idx_and_more'),
        ('reports', '0003_alter_inventoryreport_warehouse'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylocation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='masters.warehouse'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='masters.warehouse'),
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
