# Generated by Django 4.2.11 on 2026-03-20 11:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('MT', 'Metric Ton'), ('TON', 'Ton'), ('KG', 'Kilogram'), ('LB', 'Pound'), ('BBL', 'Barrel'), ('GAL', 'Gallon'), ('L', 'Liter'), ('UNIT', 'Unit')], default='MT', max_length=10)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('purity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commodities', to='commodities.category')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCommodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(blank=True, max_length=100)),
                ('min_order_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('lead_time_days', models.IntegerField(default=0)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='commodities.commodity')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodities', to='commodities.supplier')),
            ],
            options={
                'unique_together': {('supplier', 'commodity')},
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='commodities.commodity')),
            ],
            options={
                'verbose_name_plural': 'Price Histories',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['commodity', '-timestamp'], name='commodities_commodi_7cacdf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='commodity',
            index=models.Index(fields=['code'], name='commodities_code_251aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='commodity',
            index=models.Index(fields=['category'], name='commodities_categor_021b03_idx'),
        ),
    ]
