# Generated by Django 4.2.11 on 2026-04-05 16:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0002_rename_masters_comm_party_i_idx_masters_com_party_i_f7d388_idx_and_more'),
        ('commission', '0002_rename_commission_commiss_deal_id_idx_commission__deal_id_7436bf_idx_and_more'),
        ('trading', '0003_lot_purchase_sale_salelot_purchasecost_lotmovement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_entry_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('side', models.CharField(choices=[('buyer', 'Buyer Side Commission'), ('seller', 'Seller Side Commission')], max_length=20)),
                ('commission_type', models.CharField(choices=[('per_mt', 'Per MT'), ('percentage', 'Percentage'), ('fixed', 'Fixed')], max_length=20)),
                ('gross_commission', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('cpr_amount', models.DecimalField(decimal_places=2, default=0, help_text='CPR/Withholding deducted', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_receivable', models.DecimalField(decimal_places=2, help_text='gross_commission - cpr_amount', max_digits=15)),
                ('received_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_status', models.CharField(choices=[('outstanding', 'Outstanding'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], db_index=True, default='outstanding', max_length=20)),
                ('posting_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_deal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='commission.commissiondeal')),
                ('commission_lifting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commission.commissionlifting')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_ledger_entries', to='masters.party')),
            ],
            options={
                'verbose_name_plural': 'Commission Ledger Entries',
                'ordering': ['-posting_date'],
            },
        ),
        migrations.CreateModel(
            name='ThirdPartySettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_date', models.DateField()),
                ('settlement_reason', models.CharField(max_length=255)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('instruction_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('recovered', 'Recovered'), ('paid_back', 'Paid Back'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='recorded', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('original_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_original', to='masters.party')),
                ('related_commission_deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commission.commissiondeal')),
                ('third_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_intermediary', to='masters.party')),
            ],
            options={
                'ordering': ['-settlement_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_ref', models.CharField(db_index=True, max_length=50, unique=True)),
                ('payment_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('third_party', 'Third Party Payment'), ('adjustment', 'Adjustment/Credit')], max_length=20)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('cpr_amount', models.DecimalField(decimal_places=2, default=0, help_text='CPR/Withholding deducted by party', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_amount_received', models.DecimalField(decimal_places=2, help_text='gross_amount - cpr_amount', max_digits=15)),
                ('cheque_number', models.CharField(blank=True, max_length=50)),
                ('certificate_reference', models.CharField(blank=True, help_text='CPR certificate number if applicable', max_length=100)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('allocated', 'Allocated'), ('reconciled', 'Reconciled'), ('disputed', 'Disputed'), ('reversed', 'Reversed')], db_index=True, default='recorded', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to='masters.party')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_ref', models.CharField(db_index=True, max_length=50, unique=True)),
                ('payment_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('adjustment', 'Adjustment/Debit')], max_length=20)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('cpr_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_amount_paid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cheque_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('made', 'Made'), ('reconciled', 'Reconciled'), ('disputed', 'Disputed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_made', to='masters.party')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('allocation_status', models.CharField(choices=[('allocated', 'Allocated'), ('partial', 'Partial'), ('full', 'Full'), ('reversed', 'Reversed')], default='allocated', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commission_deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commission.commissiondeal')),
                ('commission_ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.commissionledgerentry')),
                ('payment_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounting.paymentmade')),
                ('payment_received', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounting.paymentreceived')),
                ('trading_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartyLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_entry_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('entry_type', models.CharField(choices=[('commission_lifting', 'Commission Lifting'), ('commission_receipt', 'Commission Receipt'), ('trading_sale', 'Trading Sale'), ('trading_purchase', 'Trading Purchase'), ('payment_received', 'Payment Received'), ('payment_made', 'Payment Made'), ('third_party_settlement', 'Third Party Settlement'), ('adjustment', 'Adjustment/Journal'), ('opening_balance', 'Opening Balance')], db_index=True, max_length=50)),
                ('business_line', models.CharField(choices=[('trading', 'Trading'), ('commission', 'Commission'), ('both', 'Both')], default='both', max_length=20)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('running_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commission_deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commission.commissiondeal')),
                ('commission_lifting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commission.commissionlifting')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='masters.party')),
                ('payment_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.paymentmade')),
                ('payment_received', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.paymentreceived')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.thirdpartysettlement')),
                ('trading_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.purchase')),
                ('trading_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.sale')),
            ],
            options={
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_ref', models.CharField(db_index=True, max_length=50, unique=True)),
                ('entry_type', models.CharField(choices=[('correction', 'Correction'), ('write_off', 'Write-off'), ('adjustment', 'Adjustment'), ('accrual', 'Accrual'), ('reversal', 'Reversal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('reason', models.TextField(help_text='Why is this journal entry needed?')),
                ('remarks', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_journals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journals', to=settings.AUTH_USER_MODEL)),
                ('credit_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_credit', to='masters.party')),
                ('debit_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_debit', to='masters.party')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CPREntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpr_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('cpr_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('certificate_number', models.CharField(blank=True, help_text='Tax authority certificate number', max_length=100)),
                ('posted_to_authority', models.BooleanField(default=False)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commission_ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpr_entry', to='accounting.commissionledgerentry')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cpr_entries', to='masters.party')),
                ('payment_received', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpr_entry', to='accounting.paymentreceived')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='thirdpartysettlement',
            index=models.Index(fields=['original_party', 'third_party'], name='accounting__origina_7b02fd_idx'),
        ),
        migrations.AddIndex(
            model_name='thirdpartysettlement',
            index=models.Index(fields=['status'], name='accounting__status_e7c63b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceived',
            index=models.Index(fields=['payment_ref'], name='accounting__payment_bf98e7_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceived',
            index=models.Index(fields=['party', '-payment_date'], name='accounting__party_i_c3c50f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceived',
            index=models.Index(fields=['status'], name='accounting__status_68839e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmade',
            index=models.Index(fields=['payment_ref'], name='accounting__payment_c1995b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmade',
            index=models.Index(fields=['party', '-payment_date'], name='accounting__party_i_dd4490_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmade',
            index=models.Index(fields=['status'], name='accounting__status_1c356b_idx'),
        ),
        migrations.AddIndex(
            model_name='partyledgerentry',
            index=models.Index(fields=['ledger_entry_no'], name='accounting__ledger__143069_idx'),
        ),
        migrations.AddIndex(
            model_name='partyledgerentry',
            index=models.Index(fields=['party', '-entry_date'], name='accounting__party_i_f5dfa5_idx'),
        ),
        migrations.AddIndex(
            model_name='partyledgerentry',
            index=models.Index(fields=['entry_type'], name='accounting__entry_t_fbc85e_idx'),
        ),
        migrations.AddIndex(
            model_name='partyledgerentry',
            index=models.Index(fields=['business_line'], name='accounting__busines_1f275c_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['journal_ref'], name='accounting__journal_3a7408_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['is_approved'], name='accounting__is_appr_029551_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionledgerentry',
            index=models.Index(fields=['ledger_entry_no'], name='accounting__ledger__981b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionledgerentry',
            index=models.Index(fields=['commission_deal', 'side'], name='accounting__commiss_a01e22_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionledgerentry',
            index=models.Index(fields=['party'], name='accounting__party_i_c898da_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionledgerentry',
            index=models.Index(fields=['payment_status'], name='accounting__payment_f306d8_idx'),
        ),
    ]
