# Generated by Django 4.2.11 on 2026-03-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='commissiondeal',
            new_name='commission__deal_id_7436bf_idx',
            old_name='commission_commiss_deal_id_idx',
        ),
        migrations.RenameIndex(
            model_name='commissiondeal',
            new_name='commission__status_db8dcb_idx',
            old_name='commission_commiss_status_idx',
        ),
        migrations.RenameIndex(
            model_name='commissiondeal',
            new_name='commission__deal_da_5547a5_idx',
            old_name='commission_commiss_deal_date_idx',
        ),
        migrations.RenameIndex(
            model_name='commissionlifting',
            new_name='commission__lifting_455c16_idx',
            old_name='commission_commiss_lifting_idx',
        ),
        migrations.RenameIndex(
            model_name='commissionlifting',
            new_name='commission__deal_id_d1583e_idx',
            old_name='commission_commiss_deal_idx',
        ),
        migrations.RenameIndex(
            model_name='commissionlifting',
            new_name='commission__lifting_f92f89_idx',
            old_name='commission_commiss_lifting_date_idx',
        ),
    ]
