# Generated by Django 4.2.11 on 2026-04-05 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0002_rename_commission_commiss_deal_id_idx_commission__deal_id_7436bf_idx_and_more'),
        ('commission', '0002_update_deal'),
    ]

    operations = [
    ]
