# Generated by Django 4.2.11 on 2026-03-20 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('trade_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('counterparty_name', models.CharField(max_length=200)),
                ('counterparty_country', models.CharField(max_length=100)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('trade_date', models.DateField()),
                ('settlement_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('executed', 'Executed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-trade_date'],
            },
        ),
        migrations.CreateModel(
            name='TradeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('price', 'Price Alert'), ('margin', 'Margin Alert'), ('position', 'Position Alert'), ('risk', 'Risk Alert'), ('system', 'System Alert')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('short_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('average_long_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_short_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_market_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
