# Generated by Django 4.2.11 on 2026-03-20 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0001_initial'),
        ('commodities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesession',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tradeposition',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commodities.commodity'),
        ),
        migrations.AddField(
            model_name='tradeposition',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tradealert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trade',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commodities.commodity'),
        ),
        migrations.AddField(
            model_name='trade',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='trading.tradesession'),
        ),
        migrations.AddField(
            model_name='trade',
            name='trader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tradeposition',
            unique_together={('trader', 'commodity')},
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['trade_id'], name='trading_tra_trade_i_b44db8_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['status'], name='trading_tra_status_252e0c_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['trader', '-trade_date'], name='trading_tra_trader__2e65e3_idx'),
        ),
    ]
