# Generated by Django 4.2.11 on 2026-03-20 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0001_initial'),
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementhistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlementhistory',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='settlements.settlement'),
        ),
        migrations.AddField(
            model_name='settlementallocation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settlements.bankaccount'),
        ),
        migrations.AddField(
            model_name='settlementallocation',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='settlements.settlement'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlement',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='trading.trade'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='settlements.settlement'),
        ),
        migrations.AlterUniqueTogether(
            name='settlementallocation',
            unique_together={('settlement', 'account')},
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['settlement_id'], name='settlements_settlem_be3a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['status'], name='settlements_status_83e9c8_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['settlement_date'], name='settlements_settlem_99f260_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_id'], name='settlements_payment_f160e6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='settlements_status_0b073d_idx'),
        ),
    ]
