# Generated by Django 4.2.11 on 2026-03-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_rename_masters_comm_party_i_idx_masters_com_party_i_f7d388_idx_and_more'),
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreport',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.warehouse'),
        ),
    ]
